# Generated by Django 2.2 on 2020-11-25 07:28

import developer.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField()),
                ('is_to_game', models.BooleanField()),
                ('status', models.CharField(choices=[('VERSION', 'VERSION'), ('GAME', 'GAME'), ('DLC', 'DLC')], default='GAME', max_length=7)),
                ('comment_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='developer.Comment')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('account', models.CharField(max_length=30)),
                ('avatar', models.ImageField(null=True, upload_to=developer.models.user_directory_path, verbose_name='头像')),
                ('introduction', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['account'],
            },
        ),
        migrations.CreateModel(
            name='DLC',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('introduction', models.TextField()),
                ('announce_date', models.DateField()),
                ('release_date', models.DateField()),
                ('create_date', models.DateField()),
                ('price', models.FloatField()),
                ('avatar', models.ImageField(null=True, upload_to=developer.models.user_directory_path, verbose_name='封面')),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentationHelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentation', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('introduction', models.TextField()),
                ('announce_date', models.DateField()),
                ('release_date', models.DateField()),
                ('create_date', models.DateField()),
                ('price', models.FloatField()),
                ('avatar', models.ImageField(null=True, upload_to=developer.models.user_directory_path, verbose_name='封面')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_developer_set', to='developer.Developer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('account', models.FloatField()),
                ('avatar', models.ImageField(upload_to='')),
                ('introduction', models.TextField()),
                ('create_date', models.DateField()),
                ('dlc', models.ManyToManyField(to='developer.DLC')),
                ('game', models.ManyToManyField(to='developer.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_up', models.BooleanField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.User')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('introduction', models.TextField()),
                ('announce_date', models.DateField()),
                ('release_date', models.DateField()),
                ('create_date', models.DateField()),
                ('price', models.FloatField()),
                ('avatar', models.ImageField(null=True, upload_to=developer.models.user_directory_path, verbose_name='封面')),
                ('file', models.FileField(upload_to='')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
                ('status', models.CharField(choices=[('VERSION', 'VERSION'), ('GAME', 'GAME'), ('DLC', 'DLC')], default='GAME', max_length=7)),
                ('dlc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='developer.DLC')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='developer.Game')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='developer.Version')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.ManyToManyField(to='developer.GameType'),
        ),
        migrations.AddField(
            model_name='dlc',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.Game'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('VERSION', 'VERSION'), ('GAME', 'GAME'), ('DLC', 'DLC')], default='GAME', max_length=7)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('price', models.FloatField()),
                ('dlc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='developer.DLC')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='developer.Game')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='developer.Version')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='dlc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='developer.DLC'),
        ),
        migrations.AddField(
            model_name='comment',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='developer.Game'),
        ),
        migrations.AddField(
            model_name='comment',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='developer.Version'),
        ),
    ]
