# Generated by Django 2.2 on 2020-12-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_auto_20201220_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='account',
            field=models.FloatField(),
        ),
    ]
