# Generated by Django 2.2.8 on 2020-12-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='files',
            field=models.FileField(null=True, upload_to='game_file/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='avatar',
            field=models.ImageField(upload_to='game_image/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='introduction',
            field=models.TextField(default=''),
        ),
    ]
