# Generated by Django 2.2 on 2020-11-26 17:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='avatar',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
