# Generated by Django 2.2 on 2020-12-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='video',
            field=models.FileField(null=True, upload_to='game_video/%Y/%m/%d/'),
        ),
    ]
