# Generated by Django 2.2 on 2020-12-24 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.CharField(blank=True, default='大家好！萌新一个！', max_length=300)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(default='avatar/defaultAv.png', upload_to='avatar/%Y/%m/%d/')),
                ('account', models.FloatField(default=0)),
                ('dlc', models.ManyToManyField(blank=True, to='game.DLC')),
                ('friend', models.ManyToManyField(blank=True, related_name='_extenduser_friend_+', to='user.ExtendUser')),
                ('game', models.ManyToManyField(blank=True, to='game.Game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['create_date'],
            },
        ),
    ]
