# Generated by Django 2.2 on 2020-12-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='dlc',
            field=models.ManyToManyField(blank=True, to='game.DLC'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='friend',
            field=models.ManyToManyField(blank=True, related_name='_extenduser_friend_+', to='user.ExtendUser'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='game',
            field=models.ManyToManyField(blank=True, to='game.Game'),
        ),
    ]
