# Generated by Django 2.2 on 2020-12-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extenduser',
            name='game',
        ),
        migrations.AddField(
            model_name='extenduser',
            name='version',
            field=models.ManyToManyField(blank=True, to='game.Version'),
        ),
    ]
