# Generated by Django 2.2 on 2020-12-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201221_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='account',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
