# Generated by Django 2.2.8 on 2020-12-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201224_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='avatar',
            field=models.ImageField(default='upload/2020/12/21/sketchpad.png', upload_to='avatar/%Y/%m/%d/'),
        ),
    ]
