# Generated by Django 2.2 on 2020-12-25 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_extenduser_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extenduser',
            name='game',
        ),
    ]
