# Generated by Django 2.2.8 on 2020-12-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201224_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='avatar',
            field=models.ImageField(default='avatar/defaultAv.png', upload_to='avatar/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='introduction',
            field=models.CharField(blank=True, default='大家好！萌新一个！', max_length=300),
        ),
    ]
